Vagrant.configure(2) do |config|
  config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nicpromisc2", "deny"]
  end
  config.vm.define "vsrx01" do |vsrx01|
    vsrx01.vm.host_name = "vsrx01"
    vsrx01.vm.network "private_network", ip: "192.168.0.11", :name => 'vboxnet10'
    vsrx01.vm.network "private_network", virtualbox__intnet: "01-to-02"
    vsrx01.vm.network "private_network", virtualbox__intnet: "03-to-01"
  end

  config.vm.define "vsrx02" do |vsrx02|
    vsrx02.vm.host_name = "vsrx02"
    vsrx02.vm.network "private_network", ip: "192.168.0.12", :name => 'vboxnet10'
    vsrx02.vm.network "private_network", virtualbox__intnet: "02-to-03"
    vsrx02.vm.network "private_network", virtualbox__intnet: "01-to-02"
  end

  config.vm.define "vsrx03" do |vsrx03|
    vsrx03.vm.host_name = "vsrx03"
    vsrx03.vm.network "private_network", ip: "192.168.0.13", :name => 'vboxnet10'
    vsrx03.vm.network "private_network", virtualbox__intnet: "03-to-01"
    vsrx03.vm.network "private_network", virtualbox__intnet: "02-to-03"
  end
end