Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ansible"
  config.vm.network "private_network", ip: "192.168.100.254"
  config.vm.network "public_network", bridge: "Ethernet adapter Local Area Connection"
  config.vm.synced_folder "files/", "/home/vagrant/playbooks/"
  config.vm.provision "shell", path: "ansible-install.sh"
end
