Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "gns3"
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.network "private_network", ip: "10.0.0.10", :adapter => 2
  config.vm.synced_folder "files/", "/home/vagrant/files", create: true
  config.vm.provision "shell", path: "./pre-install.sh"
  config.vm.provision "shell", inline: "ansible-playbook -i files/inventory files/main.yml"
  config.vm.provider :virtualbox do |vb|
   vb.customize ["modifyvm", :id, "--memory", "2048"]
   vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
