Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.synced_folder "files/", "/home/vagrant/files/"
end